import { Difficulty, CategoryId } from './types';

interface StaticWord {
  text: string;
  difficulty: Difficulty;
  category: CategoryId;
  isAdult?: boolean;
}

export const staticWordsData: StaticWord[] = [
  // --- Objects (اشیاء) ---
  { text: "خودکار", difficulty: 1, category: "objects" },
  { text: "عینک آفتابی", difficulty: 1, category: "objects" },
  { text: "قابلمه", difficulty: 1, category: "objects" },
  { text: "جاروبرقی", difficulty: 1, category: "objects" },
  { text: "چتر", difficulty: 1, category: "objects" },
  { text: "کلاه ایمنی", difficulty: 1, category: "objects" },
  { text: "کیف پول", difficulty: 1, category: "objects" },
  { text: "شانه", difficulty: 1, category: "objects" },
  { text: "ساعت مچی", difficulty: 1, category: "objects" },
  { text: "مسواک", difficulty: 1, category: "objects" },
  { text: "دستگاه مخلوط‌کن", difficulty: 3, category: "objects" },
  { text: "سشوار صنعتی", difficulty: 3, category: "objects" },
  { text: "فندک اتمی", difficulty: 3, category: "objects" },
  { text: "نخ دندان", difficulty: 3, category: "objects" },
  { text: "پیچ‌گوشتی چهارسو", difficulty: 3, category: "objects" },
  { text: "فلاسک چای", difficulty: 3, category: "objects" },
  { text: "آب‌میوه‌گیری", difficulty: 3, category: "objects" },
  { text: "سه راهی برق", difficulty: 3, category: "objects" },
  { text: "دستگاه کارت‌خوان", difficulty: 3, category: "objects" },
  { text: "کاندوم", difficulty: 1, category: "objects", isAdult: true },
{ text: "بی‌بی‌چک", difficulty: 1, category: "objects", isAdult: true },
{ text: "ژل لوبریکانت", difficulty: 3, category: "objects", isAdult: true },
{ text: "شیاف", difficulty: 3, category: "objects", isAdult: true },

  // --- Jobs (مشاغل) ---
  { text: "نانوا", difficulty: 1, category: "jobs" },
  { text: "راننده تاکسی", difficulty: 1, category: "jobs" },
  { text: "پرستار", difficulty: 1, category: "jobs" },
  { text: "آرایشگر", difficulty: 1, category: "jobs" },
  { text: "معلم", difficulty: 1, category: "jobs" },
  { text: "پلیس", difficulty: 1, category: "jobs" },
  { text: "قصاب", difficulty: 1, category: "jobs" },
  { text: "کارگر ساختمان", difficulty: 1, category: "jobs" },
  { text: "خلبان", difficulty: 1, category: "jobs" },
  { text: "آشپز", difficulty: 1, category: "jobs" },
  { text: "مهندس نرم‌افزار", difficulty: 3, category: "jobs" },
  { text: "متخصص بیهوشی", difficulty: 3, category: "jobs" },
  { text: "غواص صنعتی", difficulty: 3, category: "jobs" },
  { text: "بازاریاب تلفنی", difficulty: 3, category: "jobs" },
  { text: "کارشناس بورس", difficulty: 3, category: "jobs" },
  { text: "تعمیرکار موبایل", difficulty: 3, category: "jobs" },
  { text: "نگهبان باغ‌وحش", difficulty: 3, category: "jobs" },
  { text: "طراح لباس", difficulty: 3, category: "jobs" },
  { text: "باستان‌شناس", difficulty: 3, category: "jobs" },
  { text: "اپیلاسیون‌کار", difficulty: 1, category: "jobs", isAdult: true },
  { text: "ستاره پورن", difficulty: 3, category: "jobs", isAdult: true },

  // --- Places (اماکن) ---
  { text: "پارک", difficulty: 1, category: "places" },
  { text: "بیمارستان", difficulty: 1, category: "places" },
  { text: "مدرسه", difficulty: 1, category: "places" },
  { text: "فرودگاه", difficulty: 1, category: "places" },
  { text: "رستوران", difficulty: 1, category: "places" },
  { text: "پمپ بنزین", difficulty: 1, category: "places" },
  { text: "سینما", difficulty: 1, category: "places" },
  { text: "استخر", difficulty: 1, category: "places" },
  { text: "آرایشگاه", difficulty: 1, category: "places" },
  { text: "کتابخانه", difficulty: 1, category: "places" },
  { text: "تالار آینه", difficulty: 3, category: "places" },
  { text: "کویر لوت", difficulty: 3, category: "places" },
  { text: "بازار تجریش", difficulty: 3, category: "places" },
  { text: "تخت جمشید", difficulty: 3, category: "places" },
  { text: "غار علیصدر", difficulty: 3, category: "places" },
  { text: "پل طبیعت", difficulty: 3, category: "places" },
  { text: "حرم امام رضا", difficulty: 3, category: "places" },
  { text: "قلعه رودخان", difficulty: 3, category: "places" },
  { text: "میدان آزادی", difficulty: 3, category: "places" },
  { text: "برج میلاد", difficulty: 3, category: "places" },

  // --- Celebrities (مشاهیر) ---
  { text: "مهران مدیری", difficulty: 1, category: "celebrities" },
  { text: "عادل فردوسی‌پور", difficulty: 1, category: "celebrities" },
  { text: "محمدرضا گلزار", difficulty: 1, category: "celebrities" },
  { text: "علی دایی", difficulty: 1, category: "celebrities" },
  { text: "حسن روحانی", difficulty: 1, category: "celebrities" },
  { text: "رامبد جوان", difficulty: 1, category: "celebrities" },
  { text: "شهاب حسینی", difficulty: 1, category: "celebrities" },
  { text: "جواد عزتی", difficulty: 1, category: "celebrities" },
  { text: "نوید محمدزاده", difficulty: 1, category: "celebrities" },
  { text: "رضا عطاران", difficulty: 1, category: "celebrities" },
  { text: "احمد شاملو", difficulty: 3, category: "celebrities" },
  { text: "محمدرضا شجریان", difficulty: 3, category: "celebrities" },
  { text: "بهروز وثوقی", difficulty: 3, category: "celebrities" },
  { text: "فروغ فرخزاد", difficulty: 3, category: "celebrities" },
  { text: "پروفسور حسابی", difficulty: 3, category: "celebrities" },
  { text: "غلامرضا تختی", difficulty: 3, category: "celebrities" },
  { text: "صادق هدایت", difficulty: 3, category: "celebrities" },
  { text: "پروین اعتصامی", difficulty: 3, category: "celebrities" },
  { text: "کمال‌الملک", difficulty: 3, category: "celebrities" },
  { text: "فردوسی", difficulty: 3, category: "celebrities" },

  // --- Animals (حیوانات) ---
  { text: "گربه", difficulty: 1, category: "animals" },
  { text: "سگ", difficulty: 1, category: "animals" },
  { text: "فیل", difficulty: 1, category: "animals" },
  { text: "زرافه", difficulty: 1, category: "animals" },
  { text: "شیر", difficulty: 1, category: "animals" },
  { text: "میمون", difficulty: 1, category: "animals" },
  { text: "مرغ", difficulty: 1, category: "animals" },
  { text: "خرگوش", difficulty: 1, category: "animals" },
  { text: "ماهی", difficulty: 1, category: "animals" },
  { text: "اسب", difficulty: 1, category: "animals" },
  { text: "پلاتی‌پوس", difficulty: 3, category: "animals" },
  { text: "آفتاب‌پرست", difficulty: 3, category: "animals" },
  { text: "تنبل", difficulty: 3, category: "animals" },
  { text: "جوجه تیغی", difficulty: 3, category: "animals" },
  { text: "مارماهی", difficulty: 3, category: "animals" },
  { text: "مورچه‌خوار", difficulty: 3, category: "animals" },
  { text: "فک دریایی", difficulty: 3, category: "animals" },
  { text: "کرگدن", difficulty: 3, category: "animals" },
  { text: "پنگوئن", difficulty: 3, category: "animals" },
  { text: "پلنگ صورتی", difficulty: 3, category: "animals" },

  // --- Food (خوراکی‌ها) ---
  { text: "قرمه سبزی", difficulty: 1, category: "food" },
  { text: "کباب کوبیده", difficulty: 1, category: "food" },
  { text: "پیتزا", difficulty: 1, category: "food" },
  { text: "بستنی", difficulty: 1, category: "food" },
  { text: "ماکارونی", difficulty: 1, category: "food" },
  { text: "سالاد الویه", difficulty: 1, category: "food" },
  { text: "سیب زمینی سرخ کرده", difficulty: 1, category: "food" },
  { text: "تخم مرغ", difficulty: 1, category: "food" },
  { text: "هندوانه", difficulty: 1, category: "food" },
  { text: "نان سنگک", difficulty: 1, category: "food" },
  { text: "فسنجان", difficulty: 3, category: "food" },
  { text: "دلمه برگ مو", difficulty: 3, category: "food" },
  { text: "کوفته تبریزی", difficulty: 3, category: "food" },
  { text: "باقالاقاتوق", difficulty: 3, category: "food" },
  { text: "میرزا قاسمی", difficulty: 3, category: "food" },
  { text: "کله پاچه", difficulty: 3, category: "food" },
  { text: "ته چین مرغ", difficulty: 3, category: "food" },
  { text: "سوشی", difficulty: 3, category: "food" },
  { text: "استیک", difficulty: 3, category: "food" },
  { text: "لازانیا", difficulty: 3, category: "food" },

  // --- Proverbs (ضرب‌المثل) ---
  { text: "کوه به کوه نمیرسه آدم به آدم میرسه", difficulty: 10, category: "proverbs" },
  { text: "مرغ همسایه غازه", difficulty: 10, category: "proverbs" },
  { text: "آشپز که دوتا شد آش یا شور میشه یا بی‌نمک", difficulty: 10, category: "proverbs" },
  { text: "هر که بامش بیش برفش بیشتر", difficulty: 10, category: "proverbs" },
  { text: "مار از پونه بدش میاد دم لونش سبز میشه", difficulty: 10, category: "proverbs" },
  { text: "گربه دستش به گوشت نمیرسه میگه پیف پیف بو میده", difficulty: 10, category: "proverbs" },
  { text: "از تو حرکت از خدا برکت", difficulty: 10, category: "proverbs" },
  { text: "با یک گل بهار نمیشه", difficulty: 10, category: "proverbs" },
  { text: "دیگی که برای من نجوشه سر سگ توش بجوشه", difficulty: 10, category: "proverbs" },
  { text: "آب که سربالا بره قورباغه ابوعطا میخونه", difficulty: 10, category: "proverbs" },
  { text: "شتر دیدی ندیدی", difficulty: 10, category: "proverbs" },
  { text: "پایت را از گلیمت درازتر نکن", difficulty: 10, category: "proverbs" },
  { text: "دیوار موش داره موش هم گوش داره", difficulty: 10, category: "proverbs" },
  { text: "جیک جیک مستونت بود فکر زمستونت بود", difficulty: 10, category: "proverbs" },
  { text: "شاهنامه آخرش خوشه", difficulty: 10, category: "proverbs" },
  { text: "عجله کار شیطونه", difficulty: 10, category: "proverbs" },
  { text: "کاچی به از هیچی", difficulty: 10, category: "proverbs" },
  { text: "ماهی را هر وقت از آب بگیری تازه است", difficulty: 10, category: "proverbs" },
  { text: "نرود میخ آهنین در سنگ", difficulty: 10, category: "proverbs" },
  { text: "هر گردی گردو نیست", difficulty: 10, category: "proverbs" },
  { text: "با دم شیر بازی نکن", difficulty: 10, category: "proverbs" },
  { text: "فلفل نبین چه ریزه", difficulty: 10, category: "proverbs", isAdult: true },

  // --- Movies (فیلم و سریال) ---
  { text: "مختارنامه", difficulty: 1, category: "movies" },
  { text: "پایتخت", difficulty: 1, category: "movies" },
  { text: "اخراجی‌ها", difficulty: 1, category: "movies" },
  { text: "یوسف پیامبر", difficulty: 1, category: "movies" },
  { text: "مرد عنکبوتی", difficulty: 1, category: "movies" },
  { text: "تایتانیک", difficulty: 1, category: "movies" },
  { text: "هری پاتر", difficulty: 1, category: "movies" },
  { text: "جوکر", difficulty: 1, category: "movies" },
  { text: "شهرزاد", difficulty: 1, category: "movies" },
  { text: "فرار از زندان", difficulty: 1, category: "movies" },
  { text: "جدایی نادر از سیمین", difficulty: 3, category: "movies" },
  { text: "ابد و یک روز", difficulty: 3, category: "movies" },
  { text: "هامون", difficulty: 3, category: "movies" },
  { text: "فیلم مادر", difficulty: 3, category: "movies" },
  { text: "گشت ارشاد", difficulty: 3, category: "movies" },
  { text: "درباره الی", difficulty: 3, category: "movies" },
  { text: "بازی تاج و تخت", difficulty: 3, category: "movies" },
  { text: "برکینگ بد", difficulty: 3, category: "movies" },
  { text: "فروشنده", difficulty: 3, category: "movies" },
  { text: "متری شیش و نیم", difficulty: 3, category: "movies" },

  // --- Actions (فعالیت‌ها) ---
  { text: "مسواک زدن", difficulty: 1, category: "actions" },
  { text: "رانندگی کردن", difficulty: 1, category: "actions" },
  { text: "آشپزی کردن", difficulty: 1, category: "actions" },
  { text: "خوابیدن", difficulty: 1, category: "actions" },
  { text: "شنا کردن", difficulty: 1, category: "actions" },
  { text: "دویدن", difficulty: 1, category: "actions" },
  { text: "تلفن صحبت کردن", difficulty: 1, category: "actions" },
  { text: "حمام کردن", difficulty: 1, category: "actions" },
  { text: "جارو زدن", difficulty: 1, category: "actions" },
  { text: "ظرف شستن", difficulty: 1, category: "actions" },
  { text: "تعویض روغن ماشین", difficulty: 3, category: "actions" },
  { text: "پنچرگیری", difficulty: 3, category: "actions" },
  { text: "گره زدن کراوات", difficulty: 3, category: "actions" },
  { text: "ماهیگیری", difficulty: 3, category: "actions" },
  { text: "اسباب‌کشی", difficulty: 3, category: "actions" },
  { text: "گردگیری لوستر", difficulty: 3, category: "actions" },
  { text: "نخ کردن سوزن", difficulty: 3, category: "actions" },
  { text: "واکس زدن کفش", difficulty: 3, category: "actions" },
  { text: "اتو کردن پیراهن", difficulty: 3, category: "actions" },
  { text: "عمل جراحی قلب", difficulty: 3, category: "actions" },
];
